"""Generate CLI and Python API reference pages from public code."""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

from pyffmpegcore import FFmpegRunner, FFprobeRunner, ProgressCallback, ProgressTracker
from pyffmpegcore.cli import build_parser

REPO_ROOT = Path(__file__).resolve().parents[1]
CLI_OUTPUT = REPO_ROOT / "docs" / "reference" / "cli.md"
API_OUTPUT = REPO_ROOT / "docs" / "reference" / "python-api.md"


def parser_children(parser: argparse.ArgumentParser) -> list[tuple[str, argparse.ArgumentParser]]:
    """Return direct subcommands in their parser-defined order."""
    children = []
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        for name, child in action.choices.items():
            children.append((name, child))
    return children


def render_cli_reference() -> str:
    """Render every parser help page as deterministic Markdown."""
    lines = [
        "<!-- Generated by scripts/generate_docs.py. Do not edit by hand. -->",
        "# CLI reference",
        "",
        "This reference is generated from the same `argparse` tree used by the installed command.",
        "",
    ]

    def visit(parser: argparse.ArgumentParser, path: tuple[str, ...]) -> None:
        command = " ".join(("pyffmpegcore", *path))
        lines.extend([f"## `{command}`", "", "```text", parser.format_help().rstrip(), "```", ""])
        for name, child in parser_children(parser):
            visit(child, (*path, name))

    visit(build_parser(), ())
    return "\n".join(lines).rstrip() + "\n"


def public_methods(cls: type) -> list[tuple[str, object]]:
    """Return documented public methods defined directly by a class."""
    return [
        (name, member)
        for name, member in inspect.getmembers(cls, predicate=inspect.isfunction)
        if not name.startswith("_") and member.__qualname__.startswith(f"{cls.__name__}.")
    ]


def render_api_reference() -> str:
    """Render signatures and docstrings for the current public Python layer."""
    lines = [
        "<!-- Generated by scripts/generate_docs.py. Do not edit by hand. -->",
        "# Python API reference",
        "",
        "The Python API is synchronous and currently marked beta. Prefer explicit keyword arguments and inspect nonzero results.",
        "",
    ]
    for cls in (FFmpegRunner, FFprobeRunner, ProgressTracker, ProgressCallback):
        lines.extend([f"## `{cls.__name__}`", "", inspect.getdoc(cls) or "", ""])
        for name, member in public_methods(cls):
            signature = inspect.signature(member)
            lines.extend(
                [
                    f"### `{name}{signature}`",
                    "",
                    inspect.getdoc(member) or "No public docstring is available.",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def check_or_write(path: Path, content: str, check: bool) -> bool:
    """Write generated content, or report whether the checked-in file matches."""
    if check:
        return path.is_file() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated references are stale.")
    args = parser.parse_args(argv)

    outputs = {
        CLI_OUTPUT: render_cli_reference(),
        API_OUTPUT: render_api_reference(),
    }
    stale = [path for path, content in outputs.items() if not check_or_write(path, content, args.check)]
    if stale:
        for path in stale:
            print(f"stale generated documentation: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
