"""Generate CLI and Python API reference pages from public code."""

from __future__ import annotations

import argparse
import inspect
import sys
import textwrap
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pyffmpegcore
from pyffmpegcore.cli import build_parser

REPO_ROOT = Path(__file__).resolve().parents[1]
CLI_OUTPUT = REPO_ROOT / "docs" / "reference" / "cli.md"
API_OUTPUT = REPO_ROOT / "docs" / "reference" / "python-api.md"
DOCS_HELP_WIDTH = 100
RAW_HELP_WIDTH = 10_000


def deterministic_formatter(prog: str) -> argparse.HelpFormatter:
    """Build unwrapped help output before applying a stable cross-version wrap."""
    return argparse.HelpFormatter(prog, width=RAW_HELP_WIDTH, max_help_position=24)


def canonical_help(parser: argparse.ArgumentParser) -> str:
    """Normalize argparse wrapping, which differs between supported Python releases."""
    parser.formatter_class = deterministic_formatter
    rendered: list[str] = []
    for line in parser.format_help().rstrip().splitlines():
        if len(line) <= DOCS_HELP_WIDTH:
            rendered.append(line)
            continue
        indent = line[: len(line) - len(line.lstrip())]
        subsequent_indent = " " * len("usage: ") if line.startswith("usage: ") else indent
        rendered.extend(
            textwrap.wrap(
                line,
                width=DOCS_HELP_WIDTH,
                subsequent_indent=subsequent_indent,
                break_long_words=False,
                break_on_hyphens=False,
            )
        )
    return "\n".join(rendered)


def parser_children(parser: argparse.ArgumentParser) -> list[tuple[str, argparse.ArgumentParser]]:
    """Return direct subcommands in their parser-defined order."""
    children = []
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        for name, child in action.choices.items():
            children.append((name, child))
    return children


def render_cli_reference() -> str:
    """Render every parser help page as deterministic Markdown."""
    lines = [
        "<!-- Generated by scripts/generate_docs.py. Do not edit by hand. -->",
        "# CLI reference",
        "",
        "This reference is generated from the same `argparse` tree used by the installed command.",
        "",
    ]

    def visit(parser: argparse.ArgumentParser, path: tuple[str, ...]) -> None:
        command = " ".join(("pyffmpegcore", *path))
        lines.extend([f"## `{command}`", "", "```text", canonical_help(parser), "```", ""])
        for name, child in parser_children(parser):
            visit(child, (*path, name))

    visit(build_parser(), ())
    return "\n".join(lines).rstrip() + "\n"


def public_methods(cls: type) -> list[tuple[str, Callable[..., Any]]]:
    """Return documented public methods defined directly by a class."""
    return [
        (name, member)
        for name, member in inspect.getmembers(cls, predicate=inspect.isfunction)
        if not name.startswith("_") and member.__qualname__.startswith(f"{cls.__name__}.")
    ]


def render_api_reference() -> str:
    """Render signatures and docstrings for the current public Python layer."""
    lines = [
        "<!-- Generated by scripts/generate_docs.py. Do not edit by hand. -->",
        "# Python API reference",
        "",
        "The Python API is synchronous and currently marked beta. Prefer explicit keyword arguments and inspect nonzero results.",
        "",
    ]
    public_classes = [
        member
        for name in pyffmpegcore.__all__
        if inspect.isclass(member := getattr(pyffmpegcore, name)) and member.__module__.startswith("pyffmpegcore")
    ]
    for cls in public_classes:
        lines.extend([f"## `{cls.__name__}`", "", inspect.getdoc(cls) or "", ""])
        for name, member in public_methods(cls):
            signature = inspect.signature(member)
            lines.extend(
                [
                    f"### `{name}{signature}`",
                    "",
                    inspect.getdoc(member) or "No public docstring is available.",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def check_or_write(path: Path, content: str, check: bool) -> bool:
    """Write generated content, or report whether the checked-in file matches."""
    if check:
        return path.is_file() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated references are stale.")
    args = parser.parse_args(argv)

    outputs = {
        CLI_OUTPUT: render_cli_reference(),
        API_OUTPUT: render_api_reference(),
    }
    stale = [path for path, content in outputs.items() if not check_or_write(path, content, args.check)]
    if stale:
        for path in stale:
            print(f"stale generated documentation: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
